### ISSUE TITLE
Compilation problems after update

### ISSUE THREAD

**Issue by dbcesar** [rock-core/tools-pocolog_cpp#7]
Hi, I'm getting this error when I try to compile:

(0) tools/pocolog_cpp(/home/diego/flat_fish/dev/tools/pocolog_cpp): failed in build phase
    'make --jobserver-fds=7,8 -j' returned status 2
    see /home/diego/flat_fish/dev/install/log/tools/pocolog_cpp-build.log for details
    last 10 lines are:

         ^
    /home/diego/flat_fish/dev/tools/pocolog_cpp/src/MultiFileIndex.cpp:103:10: error: ‘it’ does not name a type
         auto it = streamToGlobalIdx.find(stream);
              ^
    /home/diego/flat_fish/dev/tools/pocolog_cpp/src/MultiFileIndex.cpp:104:8: error: ‘it’ was not declared in this scope
         if(it != streamToGlobalIdx.end())
            ^
    make[2]: *** [src/CMakeFiles/pocolog_cpp.dir/MultiFileIndex.cpp.o] Error 1
    make[1]: *** [src/CMakeFiles/pocolog_cpp.dir/all] Error 2
    make: *** [all] Error 2

**Comment by rafaelsaback** [comment]
Same here. Complementing Diego's message above:

```
home/rafaelsaback/rock/tools/pocolog_cpp/src/MultiFileIndex.cpp:25:31: error: range-based ‘for’ loops are not allowed in C++98 mode
     for(LogFile *curLogfile : logfiles)
                               ^
/home/rafaelsaback/rock/tools/pocolog_cpp/src/MultiFileIndex.cpp:27:30: error: range-based ‘for’ loops are not allowed in C++98 mode
         for(Stream *stream : curLogfile->getStreams())

/home/rafaelsaback/rock/tools/pocolog_cpp/src/MultiFileIndex.cpp:103:5: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
     auto it = streamToGlobalIdx.find(stream);
     ^
/home/rafaelsaback/rock/tools/pocolog_cpp/src/MultiFileIndex.cpp:103:10: error: ‘it’ does not name a type
     auto it = streamToGlobalIdx.find(stream);
          ^
/home/rafaelsaback/rock/tools/pocolog_cpp/src/MultiFileIndex.cpp:104:8: error: ‘it’ was not declared in this scope
     if(it != streamToGlobalIdx.end())

```

**Comment by jmachowinski** [comment]
This is c++11 code, I'll remove it

**Comment by jmachowinski** [comment]
Done
